### ISSUE TITLE
topShadowHeight=0，其它三个 = 10的时候，左上角有bug

### ISSUE THREAD

**Issue by Reagon** [linwg1988/LCardView#4]
在recyclerview的item布局中topShadowHeight=0，其它 = 10，在手机上运行就能看到每个item左上角有一处多余的颜色。

**Comment by Reagon** [comment]
> topShadowHeight

四边设置的值不等时就会出现这个bug

**Comment by linwg1988** [comment]
方便的话可以发图片到我邮箱273512894@qq.com吗？因为不是很清楚这个多余的颜色是怎么一回事

**Comment by Reagon** [comment]
> 方便的话可以发图片到我邮箱[273512894@qq.com](mailto:273512894@qq.com)吗？因为不是很清楚这个多余的颜色是怎么一回事

![image](https://user-images.githubusercontent.com/5343307/54248299-207d0600-4577-11e9-9d66-0ae7fb02ee6b.png)

**Comment by linwg1988** [comment]
使用的是1.4.2版本吗？还有手机版本是多少，以及xml的具体配置

**Comment by Reagon** [comment]
小米3c， 6.0.1系统， app:leftShadowWidth="6dp"
    app:rightShadowWidth="6dp"
    app:topShadowHeight="6dp"
    app:bottomShadowHeight="6dp"，只要这4个值有一个不同就会出现。

**Comment by linwg1988** [comment]
好的，build文件里面引用的是最新的1.4.2吗

**Comment by linwg1988** [comment]
看到了，谢谢

**Comment by Reagon** [comment]
是的，不是只有recyclerview才会出现，其它的控件也会出现

**Comment by linwg1988** [comment]
额，因为控件有局限性，使用圆角的时候，四边的阴影需要是设置同样大小的，如果想要设置不同大小的话，那么圆角就只能设置为0了，对于带圆角且四边阴影宽度不同的需求，暂时我也没想到其他什么好的办法来解决，所以先给了一个偏移量的属性来设置过渡一下，如果实在想不出什么好的解决办法，就这么一直过渡到永远了~~！

**Comment by linwg1988** [comment]
请使用最新的1.5.2版本
