### ISSUE TITLE
RecycleView嵌套LCardView时，当手指落在LCardView区域内，无法滑动整个RecycleView

### ISSUE THREAD

**Issue by q88qaz** [linwg1988/LCardView#5]
如题

**Comment by linwg1988** [comment]
> 如题

可以贴一下代码吗？我自己使用的时候并没有出现这个情况

**Comment by q88qaz** [comment]
我解决了，RecycleView嵌套LCardView，LCardView里面再嵌套1个RecycleView，我把最里面的RecycleView禁用滑动就可以了
