### ISSUE TITLE
无法显示图片和文字

### ISSUE THREAD

**Issue by vigo-liang** [linwg1988/LCardView#7]
down下来项目，运行以后不显示图片和文字，
![image](https://user-images.githubusercontent.com/7020178/67174600-326c3480-f3f5-11e9-9daa-9fe2530bcae1.png)
zhe这样修改完以后依旧显示不出来，还请指教！

**Comment by linwg1988** [comment]
我之前调试的时候有注释掉一些代码，请down最新的代码运行
