### ISSUE TITLE
是不是还不支持androidx？

### ISSUE THREAD

**Issue by q88qaz** [linwg1988/LCardView#8]
项目升级到androidx
上下左右的阴影宽度定义后却没有效果

**Comment by linwg1988** [comment]
我自己项目支持Androidx的，你使用的是什么版本的？1.5.0版本之后我对阴影尺寸进行修改了，1.5.0之后不再支持单独设置四边阴影宽度，而是使用偏移量来移动阴影位置，具体你可以看一下README.------------------ 原始邮件 ------------------
发件人: "q88qaz"<notifications@github.com>
发送时间: 2019年11月26日(星期二) 下午4:29
收件人: "linwg1988/LCardView"<LCardView@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [linwg1988/LCardView] 是不是还不支持androidx？ (#8)



项目升级到androidx
 上下左右的阴影宽度定义后却没有效果
 
&mdash;

**Comment by q88qaz** [comment]
<www.linwg.org.lib.LCardView
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_50"
            android:layout_margin="0dp"
            android:padding="0dp"
            app:bottomOffset="0dp"
            app:bottomShadowHeight="0dp"
            app:leftOffset="0dp"
            app:leftShadowWidth="0dp"
            app:rightOffset="0dp"
            app:rightShadowWidth="0dp"
            app:shadowFluidShape="linear"
            app:shadowSize="0dp"
            android:elevation="@dimen/dp_100"
            app:topOffset="@dimen/dp_20"
            app:topShadowHeight="@dimen/dp_20">

</www.linwg.org.lib.LCardView>

很奇怪啊，我这里给底部导航栏加顶部阴影，其他三个方向指定为0dp了还是有阴影，
必须加    app:shadowSize="0dp"，但是这条属性把顶部阴影也给干掉了

**Comment by q88qaz** [comment]
顶部阴影临时解决方案：
<www.linwg.org.lib.LCardView
            android:layout_width="match_parent"
            android:layout_height="@dimen/dp_50"
            app:bottomOffset="-3dp"
            app:bottomShadowHeight="-3dp"
            app:leftOffset="-3dp"
            app:leftShadowWidth="-3dp"
            app:rightOffset="-3dp"
            app:rightShadowWidth="-3dp"
            app:shadowColor="@color/blcak"
            app:shadowFluidShape="linear"
            app:topOffset="@dimen/dp_21"
            app:topShadowHeight="@dimen/dp_21">
</www.linwg.org.lib.LCardView>

仅供参考

**Comment by q88qaz** [comment]
已解决

**Comment by q88qaz** [comment]
使用版本：
implementation 'org.linwg1988:lcardview:1.5.2'

**Comment by linwg1988** [comment]
是这样用的，offset是相对于shadowSize的偏移，如果为0就是阴影没有发生偏移了
