### ISSUE TITLE
去掉了上下左右的阴影宽带，失去了灵活性！

### ISSUE THREAD

**Issue by HMY314** [linwg1988/LCardView#9]
只能设置shadowSize，导致上下卡片的间距多了一倍，且不方便调整

**Comment by linwg1988** [comment]
去掉了四边阴影宽度，但是可以设置四边阴影的偏移量啊，同样可以展示不一样的阴影宽度

**Comment by HMY314** [comment]
![image](https://user-images.githubusercontent.com/11188841/76072517-15668580-5fd3-11ea-9206-9abb913e1060.png)
两个卡片之间的间距太大，如何减小一倍？

**Comment by linwg1988** [comment]
能具体贴一下代码吗？是在java代码里面配置还是xml里面配置的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HMY314"<notifications@github.com&gt;; 
发送时间: 2020年3月6日(星期五) 下午5:52
收件人: "linwg1988/LCardView"<LCardView@noreply.github.com&gt;; 
抄送: "林文贵"<273512894@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [linwg1988/LCardView] 去掉了上下左右的阴影宽带，失去了灵活性！ (#9)





 两个卡片之间的间距太大，如何减小一倍？

**Comment by HMY314** [comment]
两个卡片代码分别在两个xml文件中，最终2个DelegateAdapter.Adapter组合在一个界面中的。

你能写一个垂直排列的两个LCardView的布局demo吗？期望两个卡片之间的间距可以随意控制。谢谢！

**Comment by linwg1988** [comment]
卡片布局在 xml 中是最外层的吗？如果是并且列表项之间的间隙都是0的话，那可能是shadowSize设置偏大导致两张卡片间距过大，从你发过来的图片来看，四边的阴影宽度是一样，但是卡片之间由于存在两个阴影，所以呈现双倍Size的阴影宽度，如果想要做到两侧间隙与卡片间距一致的话，建议缩小shadowSize，然后对卡片两侧设置Margin。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HMY314"<notifications@github.com&gt;; 
发送时间: 2020年3月6日(星期五) 晚上6:30
收件人: "linwg1988/LCardView"<LCardView@noreply.github.com&gt;; 
抄送: "林文贵"<273512894@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [linwg1988/LCardView] 去掉了上下左右的阴影宽带，失去了灵活性！ (#9)




两个卡片代码分别在两个xml文件中，最终2个DelegateAdapter.Adapter组合在一个界面中的。
 
你能写一个垂直排列的两个LCardView的布局demo吗？期望两个卡片之间的间距可以随意控制。谢谢！

**Comment by HMY314** [comment]
卡片布局在 xml 中是最外层，试过对卡片两侧设置Margin，这时两边会出现明显的突兀，比如shadowSize是10，margin是10，margin部分纯白，卡片阴影部分渐变，这不好看，且也不符合UI设计。

**Comment by linwg1988** [comment]
最好是贴一下代码哦



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HMY314"<notifications@github.com&gt;; 
发送时间: 2020年3月9日(星期一) 上午10:50
收件人: "linwg1988/LCardView"<LCardView@noreply.github.com&gt;; 
抄送: "林文贵"<273512894@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [linwg1988/LCardView] 去掉了上下左右的阴影宽带，失去了灵活性！ (#9)




卡片布局在 xml 中是最外层，试过对卡片两侧设置Margin，这时两边会出现明显的突兀，比如shadowSize是10，margin是10，margin部分纯白，卡片阴影部分渐变，这不好看，且也不符合UI设计。

**Comment by HMY314** [comment]
项目时间紧，我已用.9图替换。你这个库挺好的，建议你在demo中增加这种场景的代码，可以完善开源库，同时方便大家使用。

**Comment by linwg1988** [comment]
谢谢，有时间的话我会再去完善一下的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HMY314"<notifications@github.com&gt;; 
发送时间: 2020年3月9日(星期一) 中午11:02
收件人: "linwg1988/LCardView"<LCardView@noreply.github.com&gt;; 
抄送: "林文贵"<273512894@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [linwg1988/LCardView] 去掉了上下左右的阴影宽带，失去了灵活性！ (#9)




项目时间紧，我已用.9图替换。你这个库挺好的，建议你在demo中增加这种场景的代码，可以完善开源库，同时方便大家使用。

**Comment by linwg1988** [comment]
已上线kt0.0.1版本，有demo可以看一下
